insert into bn(id, audio, word) values (1, null, 'এক');
insert into bn(id, audio, word) values (2, null, 'দুই');
insert into bn(id, audio, word) values (3, null, 'তিন');
insert into bn(id, audio, word) values (4, null, 'চার');
insert into bn(id, audio, word) values (5, null, 'পাঁচ');
insert into bn(id, audio, word) values (6, null, 'ছয়');
insert into bn(id, audio, word) values (7, null, 'সাত');
insert into bn(id, audio, word) values (8, null, 'আট');
insert into bn(id, audio, word) values (9, null, 'নয়');
insert into bn(id, audio, word) values (10, null, 'দশ');
insert into bn(id, audio, word) values (11, null, 'এগারো');
insert into bn(id, audio, word) values (12, null, 'বারো');
insert into bn(id, audio, word) values (13, null, 'তেরো');
insert into bn(id, audio, word) values (14, null, 'চৌদ্দ');
insert into bn(id, audio, word) values (15, null, 'পনেরো');
insert into bn(id, audio, word) values (16, null, 'ষোল');
insert into bn(id, audio, word) values (17, null, 'সতেরো');
insert into bn(id, audio, word) values (18, null, 'আঠারো');
insert into bn(id, audio, word) values (19, null, 'উনিশ');
insert into bn(id, audio, word) values (20, null, 'বিশ');
insert into bn(id, audio, word) values (21, null, 'একুশ');
insert into bn(id, audio, word) values (22, null, 'বাইশ');
insert into bn(id, audio, word) values (23, null, 'তেইশ');
insert into bn(id, audio, word) values (24, null, 'চুব্বিশ');
insert into bn(id, audio, word) values (25, null, 'পঁচিশ');
insert into bn(id, audio, word) values (26, null, 'ছাব্বিশ');
insert into bn(id, audio, word) values (27, null, 'সাতাশ');
insert into bn(id, audio, word) values (28, null, 'আটাশ');
insert into bn(id, audio, word) values (29, null, 'উনত্রিশ');
insert into bn(id, audio, word) values (30, null, 'ত্রিশ');
insert into bn(id, audio, word) values (31, null, 'একত্রিশ');
insert into bn(id, audio, word) values (32, null, 'বত্রিশ');
insert into bn(id, audio, word) values (33, null, 'তেত্রিশ');
insert into bn(id, audio, word) values (34, null, 'চুত্রিশ');
insert into bn(id, audio, word) values (35, null, 'পঁত্রিশ');
insert into bn(id, audio, word) values (36, null, 'ছত্রিশ');
insert into bn(id, audio, word) values (37, null, 'সাতত্রিশ');
insert into bn(id, audio, word) values (38, null, 'আটত্রিশ');
insert into bn(id, audio, word) values (39, null, 'উনচল্লিশ');
insert into bn(id, audio, word) values (40, null, 'চল্লিশ');
insert into bn(id, audio, word) values (41, null, 'একচল্লিশ');
insert into bn(id, audio, word) values (42, null, 'বিয়াল্লিশ');
insert into bn(id, audio, word) values (43, null, 'তেতাল্লিশ');
insert into bn(id, audio, word) values (44, null, 'চুয়াল্লিশ');
insert into bn(id, audio, word) values (45, null, 'পঁয়তাল্লিশ');
insert into bn(id, audio, word) values (46, null, 'ছয়ল্লিশ');
insert into bn(id, audio, word) values (47, null, 'সাতচল্লিশ');
insert into bn(id, audio, word) values (48, null, 'আটচল্লিশ');
insert into bn(id, audio, word) values (49, null, 'উনপঞ্চাশ');
insert into bn(id, audio, word) values (50, null, 'পঞ্চাশ');
insert into bn(id, audio, word) values (51, null, 'একান্ন');
insert into bn(id, audio, word) values (52, null, 'বায়ান্ন');
insert into bn(id, audio, word) values (53, null, 'তিরান্ন');
insert into bn(id, audio, word) values (54, null, 'চুয়ান্ন');
insert into bn(id, audio, word) values (55, null, 'পঞ্চান্ন');
insert into bn(id, audio, word) values (56, null, 'ছাপ্পান্ন');
insert into bn(id, audio, word) values (57, null, 'সাতান্ন');
insert into bn(id, audio, word) values (58, null, 'আটান্ন');
insert into bn(id, audio, word) values (59, null, 'উনষাট');
insert into bn(id, audio, word) values (60, null, 'ষাট');
insert into bn(id, audio, word) values (61, null, 'একষট্টি');
insert into bn(id, audio, word) values (62, null, 'বাষট্টি');
insert into bn(id, audio, word) values (63, null, 'তিরাষট্টি');
insert into bn(id, audio, word) values (64, null, 'চুরাষট্টি');
insert into bn(id, audio, word) values (65, null, 'পঁয়ষট্টি');
insert into bn(id, audio, word) values (66, null, 'ছয়ষট্টি');
insert into bn(id, audio, word) values (67, null, 'সাতষট্টি');
insert into bn(id, audio, word) values (68, null, 'আটষট্টি');
insert into bn(id, audio, word) values (69, null, 'উনসত্তি');
insert into bn(id, audio, word) values (70, null, 'সত্তর');
insert into bn(id, audio, word) values (71, null, 'একাত্তর');
insert into bn(id, audio, word) values (72, null, 'বাহাত্তর');
insert into bn(id, audio, word) values (73, null, 'তিরাত্তর');
insert into bn(id, audio, word) values (74, null, 'চুয়াত্তর');
insert into bn(id, audio, word) values (75, null, 'পঁচাত্তর');
insert into bn(id, audio, word) values (76, null, 'ছিয়াত্তর');
insert into bn(id, audio, word) values (77, null, 'সাতাত্তর');
insert into bn(id, audio, word) values (78, null, 'আটাত্তর');
insert into bn(id, audio, word) values (79, null, 'উনাত্তর');
insert into bn(id, audio, word) values (80, null, 'আশি');
insert into bn(id, audio, word) values (81, null, 'oitenta e um');
insert into bn(id, audio, word) values (82, null, 'oitenta e dois');
insert into bn(id, audio, word) values (83, null, 'oitenta e três');
insert into bn(id, audio, word) values (84, null, 'oitenta e quatro');
insert into bn(id, audio, word) values (85, null, 'oitenta e cinco');
insert into bn(id, audio, word) values (86, null, 'oitenta e seis');
insert into bn(id, audio, word) values (87, null, 'oitenta e sete');
insert into bn(id, audio, word) values (88, null, 'oitenta e oito');
insert into bn(id, audio, word) values (89, null, 'oitenta e nove');
insert into bn(id, audio, word) values (90, null, 'noventa');
insert into bn(id, audio, word) values (91, null, 'noventa e um');
insert into bn(id, audio, word) values (92, null, 'noventa e dois');
insert into bn(id, audio, word) values (93, null, 'noventa e três');
insert into bn(id, audio, word) values (94, null, 'noventa e quatro');
insert into bn(id, audio, word) values (95, null, 'noventa e cinco');
insert into bn(id, audio, word) values (96, null, 'noventa e seis');
insert into bn(id, audio, word) values (97, null, 'noventa e sete');
insert into bn(id, audio, word) values (98, null, 'noventa e oito');
insert into bn(id, audio, word) values (99, null, 'noventa e nove');
insert into bn(id, audio, word) values (100, null, 'একশো');
