insert into hn(id, audio, word) values (1, null, 'एक');
insert into hn(id, audio, word) values (2, null, 'दो');
insert into hn(id, audio, word) values (3, null, 'तीन');
insert into hn(id, audio, word) values (4, null, 'चार');
insert into hn(id, audio, word) values (5, null, 'पाँच');
insert into hn(id, audio, word) values (6, null, 'छः');
insert into hn(id, audio, word) values (7, null, 'सात');
insert into hn(id, audio, word) values (8, null, 'आठ');
insert into hn(id, audio, word) values (9, null, 'नौ');
insert into hn(id, audio, word) values (10, null, 'दस');
insert into hn(id, audio, word) values (11, null, 'ग्यारह');
insert into hn(id, audio, word) values (12, null, 'बारह');
insert into hn(id, audio, word) values (13, null, 'तेरह');
insert into hn(id, audio, word) values (14, null, 'चौदह');
insert into hn(id, audio, word) values (15, null, 'पंद्रह');
insert into hn(id, audio, word) values (16, null, 'सोलह');
insert into hn(id, audio, word) values (17, null, 'सत्रह');
insert into hn(id, audio, word) values (18, null, 'अठारह');
insert into hn(id, audio, word) values (19, null, 'उन्नीस');
insert into hn(id, audio, word) values (20, null, 'बीस');
insert into hn(id, audio, word) values (21, null, 'इक्कीस');
insert into hn(id, audio, word) values (22, null, 'बाईस');
insert into hn(id, audio, word) values (23, null, 'तेईस');
insert into hn(id, audio, word) values (24, null, 'चौबीस');
insert into hn(id, audio, word) values (25, null, 'पच्चीस');
insert into hn(id, audio, word) values (26, null, 'छब्बीस');
insert into hn(id, audio, word) values (27, null, 'सत्ताईस');
insert into hn(id, audio, word) values (28, null, 'अट्ठाईस');
insert into hn(id, audio, word) values (29, null, 'उनतीस');
insert into hn(id, audio, word) values (30, null, 'तीस');
insert into hn(id, audio, word) values (31, null, 'इकतीस');
insert into hn(id, audio, word) values (32, null, 'बत्तीस');
insert into hn(id, audio, word) values (33, null, 'तैंतालीस');
insert into hn(id, audio, word) values (34, null, 'चौंतीस');
insert into hn(id, audio, word) values (35, null, 'पैंतालीस');
insert into hn(id, audio, word) values (36, null, 'छিযालीस');
insert into hn(id, audio, word) values (37, null, 'सैंतालीस');
insert into hn(id, audio, word) values (38, null, 'अड़तालीस');
insert into hn(id, audio, word) values (39, null, 'उनतालीस');
insert into hn(id, audio, word) values (40, null, 'चालीस');
insert into hn(id, audio, word) values (41, null, 'इकतालीस');
insert into hn(id, audio, word) values (42, null, 'बयालीस');
insert into hn(id, audio, word) values (43, null, 'तैंतालीस');
insert into hn(id, audio, word) values (44, null, 'चौवालीस');
insert into hn(id, audio, word) values (45, null, 'पैंतालीस');
insert into hn(id, audio, word) values (46, null, 'छियालीस');
insert into hn(id, audio, word) values (47, null, 'सत्तालीस');
insert into hn(id, audio, word) values (48, null, 'अट्ठालीस');
insert into hn(id, audio, word) values (49, null, 'उनपचास');
insert into hn(id, audio, word) values (50, null, 'पचास');
insert into hn(id, audio, word) values (51, null, 'इक्यावन');
insert into hn(id, audio, word) values (52, null, 'बावन');
insert into hn(id, audio, word) values (53, null, 'तिरानवे');
insert into hn(id, audio, word) values (54, null, 'चौवन');
insert into hn(id, audio, word) values (55, null, 'पचपन');
insert into hn(id, audio, word) values (56, null, 'छप्पन');
insert into hn(id, audio, word) values (57, null, 'सत्तावन');
insert into hn(id, audio, word) values (58, null, 'अट्ठावन');
insert into hn(id, audio, word) values (59, null, 'उनसठ');
insert into hn(id, audio, word) values (60, null, 'साठ');
insert into hn(id, audio, word) values (61, null, 'इकसठ');
insert into hn(id, audio, word) values (62, null, 'बासठ');
insert into hn(id, audio, word) values (63, null, 'तिरासठ');
insert into hn(id, audio, word) values (64, null, 'चौरासठ');
insert into hn(id, audio, word) values (65, null, 'पैंतालीस');
insert into hn(id, audio, word) values (66, null, 'छियासठ');
insert into hn(id, audio, word) values (67, null, 'सत्तासठ');
insert into hn(id, audio, word) values (68, null, 'अठ्ठासठ');
insert into hn(id, audio, word) values (69, null, 'उनतीस');
insert into hn(id, audio, word) values (70, null, 'सत्तानवे');
insert into hn(id, audio, word) values (71, null, 'इकहत्तर');
insert into hn(id, audio, word) values (72, null, 'बाहत्तर');
insert into hn(id, audio, word) values (73, null, 'तिहत्तर');
insert into hn(id, audio, word) values (74, null, 'चौहत्तर');
insert into hn(id, audio, word) values (75, null, 'पचहत्तर');
insert into hn(id, audio, word) values (76, null, 'छिहत्तर');
insert into hn(id, audio, word) values (77, null, 'सत्तहत्तर');
insert into hn(id, audio, word) values (78, null, 'अठहत्तर');
insert into hn(id, audio, word) values (79, null, 'उनासी');
insert into hn(id, audio, word) values (80, null, 'अस्सी');
insert into hn(id, audio, word) values (81, null, 'ochenta y uno');
insert into hn(id, audio, word) values (82, null, 'ochenta y dos');
insert into hn(id, audio, word) values (83, null, 'ochenta y tres');
insert into hn(id, audio, word) values (84, null, 'ochenta y cuatro');
insert into hn(id, audio, word) values (85, null, 'ochenta y cinco');
insert into hn(id, audio, word) values (86, null, 'ochenta y seis');
insert into hn(id, audio, word) values (87, null, 'ochenta y siete');
insert into hn(id, audio, word) values (88, null, 'ochenta y ocho');
insert into hn(id, audio, word) values (89, null, 'ochenta y nueve');
insert into hn(id, audio, word) values (90, null, 'noventa');
insert into hn(id, audio, word) values (91, null, 'noventa y uno');
insert into hn(id, audio, word) values (92, null, 'noventa y dos');
insert into hn(id, audio, word) values (93, null, 'noventa y tres');
insert into hn(id, audio, word) values (94, null, 'noventa y cuatro');
insert into hn(id, audio, word) values (95, null, 'noventa y cinco');
insert into hn(id, audio, word) values (96, null, 'noventa y seis');
insert into hn(id, audio, word) values (97, null, 'noventa y siete');
insert into hn(id, audio, word) values (98, null, 'noventa y ocho');
insert into hn(id, audio, word) values (99, null, 'noventa y nueve');
insert into hn(id, audio, word) values (100, null, 'सौ');
