insert into pr(id, audio, word) values (1, null, 'um');
insert into pr(id, audio, word) values (2, null, 'dois');
insert into pr(id, audio, word) values (3, null, 'tres');
insert into pr(id, audio, word) values (4, null, 'quatro');
insert into pr(id, audio, word) values (5, null, 'cinco');
insert into pr(id, audio, word) values (6, null, 'seis');
insert into pr(id, audio, word) values (7, null, 'sete');
insert into pr(id, audio, word) values (8, null, 'oito');
insert into pr(id, audio, word) values (9, null, 'nove');
insert into pr(id, audio, word) values (10, null, 'diez');
insert into pr(id, audio, word) values (11, null, 'onze');
insert into pr(id, audio, word) values (12, null, 'doze');
insert into pr(id, audio, word) values (13, null, 'treze');
insert into pr(id, audio, word) values (14, null, 'dorze');
insert into pr(id, audio, word) values (15, null, 'quinze');
insert into pr(id, audio, word) values (16, null, 'oize');
insert into pr(id, audio, word) values (17, null, 'dezessete');
insert into pr(id, audio, word) values (18, null, 'dezoito');
insert into pr(id, audio, word) values (19, null, 'nove');
insert into pr(id, audio, word) values (20, null, 'vinte');
insert into pr(id, audio, word) values (21, null, 'vinte e um');
insert into pr(id, audio, word) values (22, null, 'vinte e dois');
insert into pr(id, audio, word) values (23, null, 'vinte e três');
insert into pr(id, audio, word) values (24, null, 'vinte e quatro');
insert into pr(id, audio, word) values (25, null, 'vinte e cinco');
insert into pr(id, audio, word) values (26, null, 'vinte e seis');
insert into pr(id, audio, word) values (27, null, 'vinte e sete');
insert into pr(id, audio, word) values (28, null, 'vinte e oito');
insert into pr(id, audio, word) values (29, null, 'vinte e nove');
insert into pr(id, audio, word) values (30, null, 'trinta');
insert into pr(id, audio, word) values (31, null, 'trinta e um');
insert into pr(id, audio, word) values (32, null, 'trinta e dois');
insert into pr(id, audio, word) values (33, null, 'trinta e três');
insert into pr(id, audio, word) values (34, null, 'trinta e quatro');
insert into pr(id, audio, word) values (35, null, 'trinta e cinco');
insert into pr(id, audio, word) values (36, null, 'trinta e seis');
insert into pr(id, audio, word) values (37, null, 'trinta e sete');
insert into pr(id, audio, word) values (38, null, 'trinta e oito');
insert into pr(id, audio, word) values (39, null, 'trinta e nove');
insert into pr(id, audio, word) values (40, null, 'quarenta');
insert into pr(id, audio, word) values (41, null, 'quarenta e um');
insert into pr(id, audio, word) values (42, null, 'quarenta e dois');
insert into pr(id, audio, word) values (43, null, 'quarenta e três');
insert into pr(id, audio, word) values (44, null, 'quarenta e quatro');
insert into pr(id, audio, word) values (45, null, 'quarenta e cinco');
insert into pr(id, audio, word) values (46, null, 'quarenta e seis');
insert into pr(id, audio, word) values (47, null, 'quarenta e sete');
insert into pr(id, audio, word) values (48, null, 'quarenta e oito');
insert into pr(id, audio, word) values (49, null, 'quarenta e nove');
insert into pr(id, audio, word) values (50, null, 'cinquenta');
insert into pr(id, audio, word) values (51, null, 'cinquenta e um');
insert into pr(id, audio, word) values (52, null, 'cinquenta e dois');
insert into pr(id, audio, word) values (53, null, 'cinquenta e três');
insert into pr(id, audio, word) values (54, null, 'cinquenta e quatro');
insert into pr(id, audio, word) values (55, null, 'cinquenta e cinco');
insert into pr(id, audio, word) values (56, null, 'cinquenta e seis');
insert into pr(id, audio, word) values (57, null, 'cinquenta e sete');
insert into pr(id, audio, word) values (58, null, 'cinquenta e oito');
insert into pr(id, audio, word) values (59, null, 'cinquenta e nove');
insert into pr(id, audio, word) values (60, null, 'sessenta');
insert into pr(id, audio, word) values (61, null, 'sessenta e um');
insert into pr(id, audio, word) values (62, null, 'sessenta e dois');
insert into pr(id, audio, word) values (63, null, 'sessenta e três');
insert into pr(id, audio, word) values (64, null, 'sessenta e quatro');
insert into pr(id, audio, word) values (65, null, 'sessenta e cinco');
insert into pr(id, audio, word) values (66, null, 'sessenta e seis');
insert into pr(id, audio, word) values (67, null, 'sessenta e sete');
insert into pr(id, audio, word) values (68, null, 'sessenta e oito');
insert into pr(id, audio, word) values (69, null, 'sessenta e nove');
insert into pr(id, audio, word) values (70, null, 'setenta');
insert into pr(id, audio, word) values (71, null, 'setenta e um');
insert into pr(id, audio, word) values (72, null, 'setenta e dois');
insert into pr(id, audio, word) values (73, null, 'setenta e três');
insert into pr(id, audio, word) values (74, null, 'setenta e quatro');
insert into pr(id, audio, word) values (75, null, 'setenta e cinco');
insert into pr(id, audio, word) values (76, null, 'setenta e seis');
insert into pr(id, audio, word) values (77, null, 'setenta e sete');
insert into pr(id, audio, word) values (78, null, 'setenta e oito');
insert into pr(id, audio, word) values (79, null, 'setenta e nove');
insert into pr(id, audio, word) values (80, null, 'oitenta');
insert into pr(id, audio, word) values (81, null, 'восемьдесят один');
insert into pr(id, audio, word) values (82, null, 'восемьдесят два');
insert into pr(id, audio, word) values (83, null, 'восемьдесят три');
insert into pr(id, audio, word) values (84, null, 'восемьдесят четыре');
insert into pr(id, audio, word) values (85, null, 'восемьдесят пять');
insert into pr(id, audio, word) values (86, null, 'восемьдесят шесть');
insert into pr(id, audio, word) values (87, null, 'восемьдесят семь');
insert into pr(id, audio, word) values (88, null, 'восемьдесят восемь');
insert into pr(id, audio, word) values (89, null, 'восемьдесят девять');
insert into pr(id, audio, word) values (90, null, 'девяносто');
insert into pr(id, audio, word) values (91, null, 'девяносто один');
insert into pr(id, audio, word) values (92, null, 'девяносто два');
insert into pr(id, audio, word) values (93, null, 'девяносто три');
insert into pr(id, audio, word) values (94, null, 'девяносто четыре');
insert into pr(id, audio, word) values (95, null, 'девяносто пять');
insert into pr(id, audio, word) values (96, null, 'девяносто шесть');
insert into pr(id, audio, word) values (97, null, 'девяносто семь');
insert into pr(id, audio, word) values (98, null, 'девяносто восемь');
insert into pr(id, audio, word) values (99, null, 'девяносто девять');
insert into pr(id, audio, word) values (100, null, 'cem');
