insert into ru(id, audio, word) values (1, null, 'один');
insert into ru(id, audio, word) values (2, null, 'два');
insert into ru(id, audio, word) values (3, null, 'три');
insert into ru(id, audio, word) values (4, null, 'четыре');
insert into ru(id, audio, word) values (5, null, 'пять');
insert into ru(id, audio, word) values (6, null, 'шесть');
insert into ru(id, audio, word) values (7, null, 'семь');
insert into ru(id, audio, word) values (8, null, 'восемь');
insert into ru(id, audio, word) values (9, null, 'девять');
insert into ru(id, audio, word) values (10, null, 'десять');
insert into ru(id, audio, word) values (11, null, 'одиннадцать');
insert into ru(id, audio, word) values (12, null, 'двенадцать');
insert into ru(id, audio, word) values (13, null, 'тринадцать');
insert into ru(id, audio, word) values (14, null, 'четырнадцать');
insert into ru(id, audio, word) values (15, null, 'пятнадцать');
insert into ru(id, audio, word) values (16, null, 'шестнадцать');
insert into ru(id, audio, word) values (17, null, 'семнадцать');
insert into ru(id, audio, word) values (18, null, 'восемнадцать');
insert into ru(id, audio, word) values (19, null, 'девятнадцать');
insert into ru(id, audio, word) values (20, null, 'двадцать');
insert into ru(id, audio, word) values (21, null, 'двадцать один');
insert into ru(id, audio, word) values (22, null, 'двадцать два');
insert into ru(id, audio, word) values (23, null, 'двадцать три');
insert into ru(id, audio, word) values (24, null, 'двадцать четыре');
insert into ru(id, audio, word) values (25, null, 'двадцать пять');
insert into ru(id, audio, word) values (26, null, 'двадцать шесть');
insert into ru(id, audio, word) values (27, null, 'двадцать семь');
insert into ru(id, audio, word) values (28, null, 'двадцать восемь');
insert into ru(id, audio, word) values (29, null, 'двадцать девять');
insert into ru(id, audio, word) values (30, null, 'тридцать');
insert into ru(id, audio, word) values (31, null, 'тридцать один');
insert into ru(id, audio, word) values (32, null, 'тридцать два');
insert into ru(id, audio, word) values (33, null, 'тридцать три');
insert into ru(id, audio, word) values (34, null, 'тридцать четыре');
insert into ru(id, audio, word) values (35, null, 'тридцать пять');
insert into ru(id, audio, word) values (36, null, 'тридцать шесть');
insert into ru(id, audio, word) values (37, null, 'тридцать семь');
insert into ru(id, audio, word) values (38, null, 'тридцать восемь');
insert into ru(id, audio, word) values (39, null, 'тридцать девять');
insert into ru(id, audio, word) values (40, null, 'сорок');
insert into ru(id, audio, word) values (41, null, 'сорок один');
insert into ru(id, audio, word) values (42, null, 'сорок два');
insert into ru(id, audio, word) values (43, null, 'сорок три');
insert into ru(id, audio, word) values (44, null, 'сорок четыре');
insert into ru(id, audio, word) values (45, null, 'сорок пять');
insert into ru(id, audio, word) values (46, null, 'сорок шесть');
insert into ru(id, audio, word) values (47, null, 'сорок семь');
insert into ru(id, audio, word) values (48, null, 'сорок восемь');
insert into ru(id, audio, word) values (49, null, 'сорок девять');
insert into ru(id, audio, word) values (50, null, 'пятьдесят');
insert into ru(id, audio, word) values (51, null, 'пятьдесят один');
insert into ru(id, audio, word) values (52, null, 'пятьдесят два');
insert into ru(id, audio, word) values (53, null, 'пятьдесят три');
insert into ru(id, audio, word) values (54, null, 'пятьдесят четыре');
insert into ru(id, audio, word) values (55, null, 'пятьдесят пять');
insert into ru(id, audio, word) values (56, null, 'пятьдесят шесть');
insert into ru(id, audio, word) values (57, null, 'пятьдесят семь');
insert into ru(id, audio, word) values (58, null, 'пятьдесят восемь');
insert into ru(id, audio, word) values (59, null, 'пятьдесят девять');
insert into ru(id, audio, word) values (60, null, 'шестьдесят');
insert into ru(id, audio, word) values (61, null, 'шестьдесят один');
insert into ru(id, audio, word) values (62, null, 'шестьдесят два');
insert into ru(id, audio, word) values (63, null, 'шестьдесят три');
insert into ru(id, audio, word) values (64, null, 'шестьдесят четыре');
insert into ru(id, audio, word) values (65, null, 'шестьдесят пять');
insert into ru(id, audio, word) values (66, null, 'шестьдесят шесть');
insert into ru(id, audio, word) values (67, null, 'шестьдесят семь');
insert into ru(id, audio, word) values (68, null, 'шестьдесят восемь');
insert into ru(id, audio, word) values (69, null, 'шестьдесят девять');
insert into ru(id, audio, word) values (70, null, 'семьдесят');
insert into ru(id, audio, word) values (71, null, 'семьдесят один');
insert into ru(id, audio, word) values (72, null, 'семьдесят два');
insert into ru(id, audio, word) values (73, null, 'семьдесят три');
insert into ru(id, audio, word) values (74, null, 'семьдесят четыре');
insert into ru(id, audio, word) values (75, null, 'семьдесят пять');
insert into ru(id, audio, word) values (76, null, 'семьдесят шесть');
insert into ru(id, audio, word) values (77, null, 'семьдесят семь');
insert into ru(id, audio, word) values (78, null, 'семьдесят восемь');
insert into ru(id, audio, word) values (79, null, 'семьдесят девять');
insert into ru(id, audio, word) values (80, null, 'восемьдесят');
insert into ru(id, audio, word) values (81, null, '八十一');
insert into ru(id, audio, word) values (82, null, '八十二');
insert into ru(id, audio, word) values (83, null, '八十三');
insert into ru(id, audio, word) values (84, null, '八十四');
insert into ru(id, audio, word) values (85, null, '八十五');
insert into ru(id, audio, word) values (86, null, '八十六');
insert into ru(id, audio, word) values (87, null, '八十七');
insert into ru(id, audio, word) values (88, null, '八十八');
insert into ru(id, audio, word) values (89, null, '八十九');
insert into ru(id, audio, word) values (90, null, '九十');
insert into ru(id, audio, word) values (91, null, '九十一');
insert into ru(id, audio, word) values (92, null, '九十二');
insert into ru(id, audio, word) values (93, null, '九十三');
insert into ru(id, audio, word) values (94, null, '九十四');
insert into ru(id, audio, word) values (95, null, '九十五');
insert into ru(id, audio, word) values (96, null, '九十六');
insert into ru(id, audio, word) values (97, null, '九十七');
insert into ru(id, audio, word) values (98, null, '九十八');
insert into ru(id, audio, word) values (99, null, '九十九');
insert into ru(id, audio, word) values (100, null, 'сто');
