insert into sp(id, audio, word) values (1, null, 'uno');
insert into sp(id, audio, word) values (2, null, 'dos');
insert into sp(id, audio, word) values (3, null, 'tres');
insert into sp(id, audio, word) values (4, null, 'cuatro');
insert into sp(id, audio, word) values (5, null, 'cinco');
insert into sp(id, audio, word) values (6, null, 'seis');
insert into sp(id, audio, word) values (7, null, 'siete');
insert into sp(id, audio, word) values (8, null, 'ocho');
insert into sp(id, audio, word) values (9, null, 'nueve');
insert into sp(id, audio, word) values (10, null, 'diez');
insert into sp(id, audio, word) values (11, null, 'once');
insert into sp(id, audio, word) values (12, null, 'doce');
insert into sp(id, audio, word) values (13, null, 'trece');
insert into sp(id, audio, word) values (14, null, 'catorce');
insert into sp(id, audio, word) values (15, null, 'quince');
insert into sp(id, audio, word) values (16, null, 'dieciséis');
insert into sp(id, audio, word) values (17, null, 'diecisiete');
insert into sp(id, audio, word) values (18, null, 'dieciocho');
insert into sp(id, audio, word) values (19, null, 'diecinueve');
insert into sp(id, audio, word) values (20, null, 'veinte');
insert into sp(id, audio, word) values (21, null, 'veintiuno');
insert into sp(id, audio, word) values (22, null, 'veintidós');
insert into sp(id, audio, word) values (23, null, 'veintitrés');
insert into sp(id, audio, word) values (24, null, 'veinticuatro');
insert into sp(id, audio, word) values (25, null, 'veinticinco');
insert into sp(id, audio, word) values (26, null, 'veintiséis');
insert into sp(id, audio, word) values (27, null, 'veintisiete');
insert into sp(id, audio, word) values (28, null, 'veintiocho');
insert into sp(id, audio, word) values (29, null, 'veintinueve');
insert into sp(id, audio, word) values (30, null, 'treinta');
insert into sp(id, audio, word) values (31, null, 'treinta y uno');
insert into sp(id, audio, word) values (32, null, 'treinta y dos');
insert into sp(id, audio, word) values (33, null, 'treinta y tres');
insert into sp(id, audio, word) values (34, null, 'treinta y cuatro');
insert into sp(id, audio, word) values (35, null, 'treinta y cinco');
insert into sp(id, audio, word) values (36, null, 'treinta y seis');
insert into sp(id, audio, word) values (37, null, 'treinta y siete');
insert into sp(id, audio, word) values (38, null, 'treinta y ocho');
insert into sp(id, audio, word) values (39, null, 'treinta y nueve');
insert into sp(id, audio, word) values (40, null, 'cuarenta');
insert into sp(id, audio, word) values (41, null, 'cuarenta y uno');
insert into sp(id, audio, word) values (42, null, 'cuarenta y dos');
insert into sp(id, audio, word) values (43, null, 'cuarenta y tres');
insert into sp(id, audio, word) values (44, null, 'cuarenta y cuatro');
insert into sp(id, audio, word) values (45, null, 'cuarenta y cinco');
insert into sp(id, audio, word) values (46, null, 'cuarenta y seis');
insert into sp(id, audio, word) values (47, null, 'cuarenta y siete');
insert into sp(id, audio, word) values (48, null, 'cuarenta y ocho');
insert into sp(id, audio, word) values (49, null, 'cuarenta y nueve');
insert into sp(id, audio, word) values (50, null, 'cincuenta');
insert into sp(id, audio, word) values (51, null, 'cincuenta y uno');
insert into sp(id, audio, word) values (52, null, 'cincuenta y dos');
insert into sp(id, audio, word) values (53, null, 'cincuenta y tres');
insert into sp(id, audio, word) values (54, null, 'cincuenta y cuatro');
insert into sp(id, audio, word) values (55, null, 'cincuenta y cinco');
insert into sp(id, audio, word) values (56, null, 'cincuenta y seis');
insert into sp(id, audio, word) values (57, null, 'cincuenta y siete');
insert into sp(id, audio, word) values (58, null, 'cincuenta y ocho');
insert into sp(id, audio, word) values (59, null, 'cincuenta y nueve');
insert into sp(id, audio, word) values (60, null, 'sesenta');
insert into sp(id, audio, word) values (61, null, 'sesenta y uno');
insert into sp(id, audio, word) values (62, null, 'sesenta y dos');
insert into sp(id, audio, word) values (63, null, 'sesenta y tres');
insert into sp(id, audio, word) values (64, null, 'sesenta y cuatro');
insert into sp(id, audio, word) values (65, null, 'sesenta y cinco');
insert into sp(id, audio, word) values (66, null, 'sesenta y seis');
insert into sp(id, audio, word) values (67, null, 'sesenta y siete');
insert into sp(id, audio, word) values (68, null, 'sesenta y ocho');
insert into sp(id, audio, word) values (69, null, 'sesenta y nueve');
insert into sp(id, audio, word) values (70, null, 'setenta');
insert into sp(id, audio, word) values (71, null, 'setenta y uno');
insert into sp(id, audio, word) values (72, null, 'setenta y dos');
insert into sp(id, audio, word) values (73, null, 'setenta y tres');
insert into sp(id, audio, word) values (74, null, 'setenta y cuatro');
insert into sp(id, audio, word) values (75, null, 'setenta y cinco');
insert into sp(id, audio, word) values (76, null, 'setenta y seis');
insert into sp(id, audio, word) values (77, null, 'setenta y siete');
insert into sp(id, audio, word) values (78, null, 'setenta y ocho');
insert into sp(id, audio, word) values (79, null, 'setenta y nueve');
insert into sp(id, audio, word) values (80, null, 'ochenta');
insert into sp(id, audio, word) values (81, null, 'واحد و ثمانون');
insert into sp(id, audio, word) values (82, null, 'اثنان و ثمانون');
insert into sp(id, audio, word) values (83, null, 'ثلاثة و ثمانون');
insert into sp(id, audio, word) values (84, null, 'أربعة و ثمانون');
insert into sp(id, audio, word) values (85, null, 'خمسة و ثمانون');
insert into sp(id, audio, word) values (86, null, 'ستة و ثمانون');
insert into sp(id, audio, word) values (87, null, 'سبعة و ثمانون');
insert into sp(id, audio, word) values (88, null, 'ثمانية و ثمانون');
insert into sp(id, audio, word) values (89, null, 'تسعة و ثمانون');
insert into sp(id, audio, word) values (90, null, 'تسعون');
insert into sp(id, audio, word) values (91, null, 'واحد و تسعون');
insert into sp(id, audio, word) values (92, null, 'اثنان و تسعون');
insert into sp(id, audio, word) values (93, null, 'ثلاثة و تسعون');
insert into sp(id, audio, word) values (94, null, 'أربعة و تسعون');
insert into sp(id, audio, word) values (95, null, 'خمسة و تسعون');
insert into sp(id, audio, word) values (96, null, 'ستة و تسعون');
insert into sp(id, audio, word) values (97, null, 'سبعة و تسعون');
insert into sp(id, audio, word) values (98, null, 'ثمانية و تسعون');
insert into sp(id, audio, word) values (99, null, 'تسعة و تسعون');
insert into sp(id, audio, word) values (100, null, 'cien');
